// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT51k023V-sIPb_KIQI0b8XFYlDMFxDdQ',
    appId: '1:1057740475655:web:ac477dd5ffc00eae8689a2',
    messagingSenderId: '1057740475655',
    projectId: 'flutter-cook-b3162',
    authDomain: 'flutter-cook-b3162.firebaseapp.com',
    storageBucket: 'flutter-cook-b3162.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfF0T4HJ8L0EjCbbcSgL-XYFHq_s9BUPM',
    appId: '1:1057740475655:android:130a7c63ae37c6018689a2',
    messagingSenderId: '1057740475655',
    projectId: 'flutter-cook-b3162',
    storageBucket: 'flutter-cook-b3162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEaJJ6nHKt5wy_H1XiiSvgDrMB32IELQA',
    appId: '1:1057740475655:ios:e4837128e068084c8689a2',
    messagingSenderId: '1057740475655',
    projectId: 'flutter-cook-b3162',
    storageBucket: 'flutter-cook-b3162.appspot.com',
    iosBundleId: 'com.xulitos.cookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEaJJ6nHKt5wy_H1XiiSvgDrMB32IELQA',
    appId: '1:1057740475655:ios:9d3841d301646fdc8689a2',
    messagingSenderId: '1057740475655',
    projectId: 'flutter-cook-b3162',
    storageBucket: 'flutter-cook-b3162.appspot.com',
    iosBundleId: 'com.xulitos.cookapp.RunnerTests',
  );
}
